"""ondelete

Revision ID: 5a7b6f5b8663
Revises: 0d00e4b54726
Create Date: 2024-02-23 14:31:39.712111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7b6f5b8663'
down_revision: Union[str, None] = '0d00e4b54726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('carrito_ibfk_1', 'carrito', type_='foreignkey')
    op.create_foreign_key(None, 'carrito', 'pedido', ['pedidoForaneo'], ['idPedido'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carrito', type_='foreignkey')
    op.create_foreign_key('carrito_ibfk_1', 'carrito', 'pedido', ['pedidoForaneo'], ['idPedido'])
    # ### end Alembic commands ###
