"""paymeny method imagen

Revision ID: 7b558a57fff9
Revises: 5a7b6f5b8663
Create Date: 2024-02-24 13:43:30.913986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b558a57fff9'
down_revision: Union[str, None] = '5a7b6f5b8663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Payment_method', sa.Column('imagen', sa.String(length=4096), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Payment_method', 'imagen')
    # ### end Alembic commands ###
